services:
  - type: web
    name: authenhire
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_HUVowPtFiI46@ep-long-dream-atmzf4mh-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: PORT
        value: 8080
